services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./dev.db
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db

networks:
  default:
    name: frontend-network
