import { Header } from "@/components/header/Header";
import { Main } from "@/components/main/Main";
import { Providers } from "@/components/providers/Providers";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { cn } from "../lib/utils";
import "./globals.css";

const montserrat = Montserrat({
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn(montserrat.className, "antialiased")}>
				<Providers>
					<Header />
					<Main>{children}</Main>
				</Providers>
			</body>
		</html>
	);
}
